### ISSUE TITLE
TODO before IS19 TUTORIAL

### ISSUE THREAD

**Issue by kan-bayashi** [kan-bayashi/INTERSPEECH19_TUTORIAL#3]
- [ ] Update README
    - [ ] Add link to slides
    - [x] Add link to colab
    - [ ] Add Google form to score the tutorial
- [x] Prepare wavenet demo notebook
- [x] Prepare sprocket demo notebook
- [x] Add colab link to the header of notebook
- [ ] Prepare notes for presentation (push to another branch `presentation`)
- [ ] Calculate required time in Google Colab
